### ISSUE TITLE
Tradução para portugues não muda

### ISSUE THREAD

**Issue by ricktwster** [php/doc-pt_br#131]
From manual page: https://php.net/class.event
no Change language: 
quando coloco para Brazilian Portuguese

ele volta para o Ingles

**Comment by lhsazevedo** [comment]
Olá @ricktwster, obrigado pelo aviso e parabéns pela sua primeira issue.

Conferi aqui e realmente essa página ainda não foi traduzida... O manual exibe a versão em inglês como contingência.
Temos [várias](http://doc.php.net/revcheck.php?p=missfiles&lang=pt_br) páginas aguardando a tradução e eventualmente esta será traduzida por algum membro da comunidade.

Caso você tenha interesse em ajudar, suas contribuições serão muito bem-vindas! O @alfsb preparou um guia com tudo que você precisa saber pra começar: https://github.com/php/doc-pt_br/wiki.

**Comment by ricktwster** [comment]
> Olá @ricktwster, obrigado pelo aviso e parabéns pela sua primeira issue.
> 
> Conferi aqui e realmente essa página ainda não foi traduzida... O manual exibe a versão em inglês como contingência. Temos [várias](http://doc.php.net/revcheck.php?p=missfiles&lang=pt_br) páginas aguardando a tradução e eventualmente esta será traduzida por algum membro da comunidade.
> 
> Caso você tenha interesse em ajudar, suas contribuições serão muito bem-vindas! O @alfsb preparou um guia com tudo que você precisa saber pra começar: https://github.com/php/doc-pt_br/wiki.
