### ISSUE TITLE
Atualizar tradução da função uniqid

### ISSUE THREAD

**Issue by lhsazevedo** [php/doc-pt_br#134]
Atualizar tradução da função `uniqid`: https://www.php.net/manual/pt_BR/function.uniqid.php

Criando a issue apenas para reservar a tradução mesmo, farei em breve.

**Comment by Meann18** [comment]
Pls help me

**Comment by Meann18** [comment]
> Atualizar tradução da função `uniqid`: https://www.php.net/manual/pt_BR/function.uniqid.php
> 
> Criando a issue apenas para reservar a tradução mesmo, farei em breve.

Pls help me

**Comment by alfsb** [comment]
Issue a mais de três meses sem atualizações.
