### ISSUE TITLE
brazilian portuguese getopt  incomplete documentation

### ISSUE THREAD

**Issue by sparcbr** [php/doc-pt_br#135]
From manual page: https://php.net/pt_BR/function.getopt
$rest_index argument  is missing from function definition
Also shows empty description for $longopts

---

**Comment by lhsazevedo** [comment]
Olá @sparcbr, obrigado pelo aviso!

Conferi aqui no [revcheck](http://doc.php.net/revcheck.php?p=misstags&lang=pt_br) e a tradução desta função realmente está desatualizada. A última sincronização [foi em 2011](https://github.com/php/doc-pt_br/blob/f7386fa5f5948ffc4dfcc5e68ad46d3bd681a6ee/reference/info/functions/getopt.xml). Temos várias páginas aguardando tradução ou sincronização e eventualmente esta será traduzida por algum membro da comunidade.

Caso você tenha interesse em ajudar, suas contribuições serão muito bem-vindas! O @alfsb preparou um guia com tudo que você precisa saber pra começar: https://github.com/php/doc-pt_br/wiki. Se tiver dúvidas, pode entrar em contato comigo.

**Comment by alfsb** [comment]
Arquivo atualizado. Logo deve aparecer publicado no site e espelhos.
