### ISSUE TITLE
Erro de digitação no texto - unction.highlight-file

### ISSUE THREAD

**Issue by tiagofrancafernandes** [php/doc-pt_br#137]
From manual page: [https://php.net/function.highlight-file](https://www.php.net/manual/pt_BR/function.highlight-file.php#refsect1-function.highlight-file-notes)

---

Erro de digitação no texto:

Cuidados devem ser **toamdos** quando utilizando a função highlight_file() para prevenir que você não revele informações sensíveis inadivertidamente, como senhas e outros tipos de informações que possam criar risco de **seguranaça**. 

##### Suggestion

```suggestion
Cuidados devem ser tomados quando utilizando a função highlight_file() para prevenir que você não revele informações sensíveis inadivertidamente, como senhas e outros tipos de informações que possam criar risco de segurança.

```

##### Diff

```diff
- Cuidados devem ser toamdos quando utilizando a função highlight_file() para prevenir que você não revele informações sensíveis inadivertidamente, como senhas e outros tipos de informações que possam criar risco de seguranaça. 
+ Cuidados devem ser tomados quando utilizando a função highlight_file() para prevenir que você não revele informações sensíveis inadivertidamente, como senhas e outros tipos de informações que possam criar risco de segurança. 

```

**Comment by alfsb** [comment]
Corrigido. E aproveitei para atualizar o arquivo. Obrigado pelo aviso!
