### ISSUE TITLE
wip: language/namespaces.xml

### ISSUE THREAD

**Issue by alfsb** [php/doc-pt_br#150]
Temos mais um arquivo Work In Progress (wip) no repositório, o `language/namespaces.xml`. Para ajudar a coordenar as traduções e evitar choques, segue a lista de IDs do arquivo. Basta dar um aviso aqui, que reserva o ID por uma semana para a pessoa... Embora se espera que avise bem em cima de fazer uma tradução. Claro que, pode fazer tradução sem avisar, mas isso acaba complicando um pouco de ser conflito por esforço duplicado.

```
language.namespaces.rationale             // lhsazevedo     pr147 ok
language.namespaces.definition            // lhsazevedo     pr149 ok
language.namespaces.nested                // alfsb          pr157 ok
language.namespaces.definitionmultiple    // lhsazevedo     pr160 ok
language.namespaces.basics                // alfsb          pr177 ok
language.namespaces.dynamic               // lhsazevedo     pr199 ok
language.namespaces.nsconstants           // lhsazevedo     pr199 ok
language.namespaces.importing 
language.namespaces.importing.scope
language.namespaces.importing.group
language.namespaces.global                // lhsazevedo     pr159 ok
language.namespaces.fallback              // willian-rosa   pr229 ok
language.namespaces.rules                 // willian-rosa   pr222 ok
language.namespaces.faq                   // nawarian       pr188 ok
language.namespaces.faq.shouldicare       // nawarian       pr188 ok
language.namespaces.faq.globalclass       // nawarian       pr188 ok
language.namespaces.faq.innamespace       // nawarian       pr188 ok
language.namespaces.faq.full              // nawarian       pr188 ok
language.namespaces.faq.qualified         // willian-rosa   pr222 ok
language.namespaces.faq.shortname1        // willian-rosa   pr222 ok
language.namespaces.faq.shortname2        // willian-rosa   pr222 ok
language.namespaces.faq.conflict          // willian-rosa   pr222 ok
language.namespaces.faq.nested            // willian-rosa   pr222 ok
language.namespaces.faq.quote             // willian-rosa   pr222 ok
language.namespaces.faq.constants         // alfsb                ok
language.namespaces.faq.builtinconst      // alfsb                ok

dos2unix, revisão do compilado
```

**Comment by alfsb** [comment]
language.namespaces.rationale - lhsazevedo - Revisão e tradução.

**Comment by alfsb** [comment]
language.namespaces.definition - lhsazevedo - Tradução.

**Comment by alfsb** [comment]
Acabei de acertar a tag de revisão desse arquivo, que estava faltando. Super ultra liberado para quem quiser pegar trechos (ou o arquivo todo!) para traduzir).

**Comment by lhsazevedo** [comment]
Reservando `language.namespaces.global`

**Comment by lhsazevedo** [comment]
Traduzi e esqueci de reservar o `language.namespaces.definitionmultiple`

**Comment by alfsb** [comment]
Fazendo uma chamada geral, para pedir contribuintes e finalizar esse `wip`.

E reservando `language.namespaces.faq.builtinconst`.

**Comment by alfsb** [comment]
Reservando `language.namespaces.faq.constants`.

**Comment by lhsazevedo** [comment]
Reservando `language.namespaces.basics`

**Comment by nawarian** [comment]
Reservando `language.namespaces.faq`

**Comment by nawarian** [comment]
Reservando os seguintes itens:

* `language.namespaces.faq.shouldicare`
* `language.namespaces.faq.globalclass`
* `language.namespaces.faq.innamespace`
* `language.namespaces.faq.full`

**Comment by lhsazevedo** [comment]
Reservando `language.namespaces.dynamic`.

Ah, o `language.namespaces.basics` já foi traduzido no PR #177, faltou atualizar a lista.

**Comment by alfsb** [comment]
Opa, atualizado!

E até, em complemento ao https://github.com/php/doc-pt_br/issues/194 , podem fazer reservas de várias seções, ou mesmo do arquivo inteiro. Essa separação por seções meio que foi por conta da grande quantidade de ofertas de ajuda que chegaram, e para lidar com wip, que é um arquivo parcialmente traduzido.

Mas quanto antes sair da situação de parcialmente traduzido, tão melhor.

**Comment by willian-rosa** [comment]
Reservando:
- anguage.namespaces.faq.qualified
- language.namespaces.faq.shortname1
- language.namespaces.faq.shortname2
- language.namespaces.faq.conflict
- language.namespaces.faq.nested
- language.namespaces.faq.quote 
- language.namespaces.fallback
- language.namespaces.rules

**Comment by lhsazevedo** [comment]
O PR #199 traduz as seguintes seções:

- `language.namespaces.dynamic`
- `language.namespaces.nsconstants`

**Comment by alfsb** [comment]
> O PR #199 traduz as seguintes seções:

Enviado e anotado. Já tem outras seções reservadas, agora faltam bem pouco para encaminhar e fechar esse wip. Anotei também umas tarefas finais, normalizar os fim de linha desse arquivo e fazer uma revisão normalizadora após tudo pronto, dado o trabalho a várias mãos num único grande arquivo.

**Comment by cautnew** [comment]
Galera, posso fazer a seção `language.namespaces.fallback`?

**Comment by willian-rosa** [comment]
@cautnew estou traduzindo o fallback

**Comment by alfsb** [comment]
> Galera, posso fazer a seção `language.namespaces.fallback`?

Esse já está reservado. Livres as seções `importing`, e tem outro arquivo wip também, precisando de traduções.

**Comment by cautnew** [comment]
Show! Vou pegar a `importing`, então. :)
Obrigado, Gente! 👍

**Comment by alfsb** [comment]
Bom, pelas minhas rápidas contas, todo arquivo reservado. As reservas caem depois de três meses. Tem um outro arquivo em wip para quem quiser colaborar: https://github.com/php/doc-pt_br/issues/146

Ele não está fatiado em IDs, que é algo que funcionou aqui. Vou encaminhar de alterar isso no issue 146.

**Comment by alfsb** [comment]
Após três meses sem atualizações, liberando as reservas.

Peço a quem se candidatar de avisar já no dia que for fazer tradução.

A parte do `dos2unix` não fazer agora. Esperar o arquivo inteiro passar, já que é potencialmente uma alteração que afetará todo o arquivo.

**Comment by alfsb** [comment]
Bom, na ausência de outra pessoa pegar esse trechinho que falta, eu mesmo devo fazer nesse final de semana. Se alguém quiser pegar para fazer, avisa aqui, mas imediatamente antes de já começar a fazer.

**Comment by lhsazevedo** [comment]
Eu até pegaria mas não vou ter tempo antes de você começar @alfsb. Mas tudo bem, aqui não falta trabalho rs

**Comment by adielcristo** [comment]
Valeu pelo esforço para atualizar esse arquivo, pessoal. @alfsb Se não tiver começado vou pegar o arquivo para traduzir o que falta e revisar.

**Comment by alfsb** [comment]
> Valeu pelo esforço para atualizar esse arquivo, pessoal. @alfsb Se não tiver começado vou pegar o arquivo para traduzir o que falta e revisar.

Vish. Eu cometi um erro. Vim ver de manhã se alguém já tinha reservado, mas não postei eu mesmo a reserva. Acabei de subir ele. E pior, passei o dos2unix, então certeza que qualquer coisa que tiver nele vai dar conflito em todas as linhas.

Tire uma cópia, antes de subir, e pode subir a sua versão quando terminar. Depois, daí direto fechar esse issue.

**Comment by alfsb** [comment]
Mas pela experiência desse caso, cabo a rabo, eu provavelmente não vou mais aceitar arquivos wip comitados no repositório. 

Agora que o GitHub entende melhor PR em forks de forks, futuros wips serão trabalhados direto nos repositórios de quem começar, e na ausência de progressos nesses repositórios, quem for assumir a tradução puxa para si a alteração no seu próprio fork.

Deu muito trabalho manter o wip *e* coordenar a aceleração de wip, fora os esforços duplicados.

**Comment by adielcristo** [comment]
Entendo. É realmente complicado coordenar essas alterações, ainda mais quando não temos uma constância no fluxo de trabalho (o que é normal dada a disponibilidade de cada um).

Eu comecei a revisar o status geral do projeto e a testar alguns fluxos de trabalho. Criei algumas issues relacionadas às tarefas dessa semana e mais na frente atualizo de acordo com os resultados.

Um caso parecido é o do arquivo `languages-snippets.ent` que comecei hoje. Nesse caso criei um branch para enviar as alterações parciais e um dos pontos que estou avaliando nesse processo, além do tamanho do arquivo, é o quão rápido o arquivo original está mudando e qual o esforço necessário para acompanhar essas mudanças.

**Comment by alfsb** [comment]
O `languages-snippets.ent` provavelmente precisaria de um translation fest só para ele, ou, ainda, de uma formulação diferente. Algo como fatiar ele automaticamente, gerar algumas centenas de sub arquivos, traduzir esses sub arquivos, e dos sub arquivos gerar o `languages-snippets.ent` que tivesse apenas as partes sincronizadas.

Mas vou esperar ver se ti consegue sincronizar ele inteiro. As vezes que eu tentei acabei desanimado, de tão longo/eclético ele é. Caso a ideia de trabalhar num `languages-snippets.ent` fatiado seja interessante, dá um aviso, que abrimos um issue só para isso, e eu ajudo aí a tentar vencer esse monstruoso arquivo.

**Comment by adielcristo** [comment]
@alfsb Revisão finalizada.
