### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by carlos-landeira** [php/doc-pt_br#166]
![image](https://user-images.githubusercontent.com/70922382/194103291-2e3f745d-91e1-481e-a654-6f1e713d5a28.png)

No link: https://www.php.net/manual/pt_BR/language.references.pass.php

Está escrito "avido" ao invés de "aviso"

**Comment by carlos-landeira** [comment]
Além do comentário abaixo esta em inglês

**Comment by alfsb** [comment]
Olá, corrigido. Logo deve aparecer no site oficial e espelhos.
