### ISSUE TITLE
Missing Portuguese translation

### ISSUE THREAD

**Issue by francis1084** [php/doc-pt_br#17]
From manual page: https://php.net/filter.filters.sanitize

---

**Comment by alfsb** [comment]
@adielcristo , aproveitei que tive um dia livre hoje para tentar uma correção aqui. A conferir se na próxima compilação o problema já aparece corrigido.

**Comment by adielcristo** [comment]
Muito obrigado, @alfsb!

**Comment by alfsb** [comment]
Opa, de nada. Essa foi um tanto complicado porque o arquivo não estava sendo criado por cota de mais de um arquivo em paralelo, e daí até achar quais eram foi um tempo.

Fechando o bug dado que a página agora aparece compilada no pt_BR.
