### ISSUE TITLE
Retirar o @ dos cabeçalhos

### ISSUE THREAD

**Issue by alfsb** [php/doc-pt_br#175]
Um pouco de contexto, no começo a documentação utilizava CVS, que por sua vez usava uma credencial checada internamente contra um sistema interno do PHP. Depois a documentação foi migrada para SVN, mantendo o sistema, depois para um Git interno, no mesmo sistema. Nessa época começamos a aceitar commits via uma "ponte git", e os commits vindos dessa ponte eram anotados com um `@` na revtag.

Pois bem. Hoje em dia a documentação toda ocorre no GitHub, a ponte não existe mais, mas existem ainda as credenciais internas e as credenciais GitHub, marcadas sem e com arroba, respectivamente.

Minha sugestão é remover essa distinção. Especificamente, remover a necessidade do `@` na revtag. As justificativas são:

1. A distinção hoje em dia é quase nula entre eles;
2. Ainda que exista o risco de colisão de nomes, porém isso não ocorre na nossa tradução;
3. Todo o sistema de controle hoje é github, as credenciais internas não funcionam mais.

O que mudaria na prática é remover a menção de colocar `@` que hoje existe no wiki. E num futuro distante, dar uma limpada de todos os arrobas das revtags.

Deixo esse issue aberto para saber se há alguma questão negativa ou impacto que deva ser considerado antes de seguir nessa direção, ou pelo contrário, se apoio.

**Comment by MauricioFauth** [comment]
E quando alguém possua credencial do SVN que seja diferente do GitHub? Por exemplo, a minha é MauricioFauth no GitHub e somente mauricio no SVN.

Devo começar a anotar com MauricioFauth pra ficar consistente com novos contribuidores?

**Comment by alfsb** [comment]
Ainda não mude, bora esperar umas semanas, ver para onde a discussão anda, antes de fazer algo.

Isso dito, o que eu penso fazer nesse caso é padronizar, usando daí o `translations.xml`. Escolhe um nick só, coloca ele no `translations.xml`, e daí faz um mass update nas revtags para o nick escolhido.

Isso aliás torna o processo todo independente das credenciais, o que faz mais sentido hoje em dia que antigamente.

**Comment by alfsb** [comment]
Um update, que provavelmente eu devo dar encaminhamento nisso.

Basicamente vou remover a menção dos `@` no wiki, e possivelmente montar um script para remover os @ de todos os revtag da tradução brasileira.

Comentários extras ou voluntário para fazer esse script? É um bom exercício de PHP e de como lidar com um pull request de centenas a milhares de arquivos.

**Comment by alfsb** [comment]
Já comecei a dar uma revisão nos wikis, e logo mais devo chegar no ponto desse issue aqui. Para todos os efeitos, já podem ignorar o acréscimo do `@` na tag de revisão, que logo eles serão retirados em massa dos arquivos.

**Comment by alfsb** [comment]
Removido menção de `@` dos documentos, removido de todos os revtag. Testei antes de subir, mas se perceberem algum efeito colateral, só avisar.

Eu fiquei bem tentado a passar um `dos2unix` em todos os arquivos, mais um rtrim por linha e codificação forçada para utf8, mas... iria gerar um commit muito maior, sem tanta utilidade. Um dia que o manual estiver menos desatualizados, pensar em fazer isso.
