### ISSUE TITLE
Ajustes para Wiki - Situação atual

### ISSUE THREAD

**Issue by rafaelbernard** [php/doc-pt_br#184]
(Tentei enviar pela lista de discussão mas não consegui):

Olá, pessoal. Como não posso mandar um PR para a Wiki, que está fantástica com as últimas alterações, algumas coisa que vi hoje, ao reler as orientações:

(1) https://github.com/php/doc-pt_br/wiki/Roteiro-Git#passo-1-atualizando-os-fontes
O `cd base` deveria ser alterado para `cd doc-base`, pois é o nome do diretório do doc-base que indicamos no comando anterior.

(2) https://github.com/php/doc-pt_br/wiki/Roteiro-Git#passo-1-atualizando-os-fontes
O mesmo poderia ser corrigido na dica de criar o arquivo `conf.sh`, com o adicional de que poderíamos também aproveitar e colocar o hashbang no conteúdo do arquivo.

```
#!/bin/bash
(cd doc-base;  git pull)
(cd en;        git pull)
cd pt_BR
git fetch upstream
git checkout master
git merge upstream/master -m "Upstream merge."
git status
cd ..
php doc-base/configure.php --with-lang=pt_BR --enable-xml-details
```

(3) https://github.com/php/doc-pt_br/wiki/Situa%C3%A7%C3%A3o-atual
Corrigir a query string dos links de `pr_BR` para `pt_br`

Mais uma vez, ressalto que o trabalho na Wiki e dos tradutores oficiais é fantástico. Espero um dia ter contribuições suficientes para entrar no time. Enquanto isso, vou enviando meus PRs. )))

Grande abraço,
Rafael

**Comment by alfsb** [comment]
Olá Rafael! Muito obrigado pelas sugestões e apontamentos. Fiz as correções, aproveitei para dar uma revisão no Situação Atual.
