### ISSUE TITLE
Página não traduzida

### ISSUE THREAD

**Issue by carlos-landeira** [php/doc-pt_br#186]
Na página referente à função `iconv` (https://www.php.net/manual/pt_BR/function.iconv.php), 95% dela está em inglês, com apenas algumas palavras em português.

**Comment by lhsazevedo** [comment]
Olá @carlos-landeira, obrigado pelo aviso!

Conferi aqui no [revcheck](http://doc.php.net/revcheck.php?p=missfiles&lang=pt_br) e realmente esse arquivo consta como não traduzido. Temos várias páginas aguardando tradução ou sincronização e eventualmente esta será traduzida por algum membro da comunidade.

Caso você tenha interesse em ajudar, suas contribuições serão muito bem-vindas! O @alfsb preparou um guia com tudo que você precisa saber pra começar: https://github.com/php/doc-pt_br/wiki. Se tiver dúvidas, pode entrar em contato comigo.

**Comment by alfsb** [comment]
Olá @carlos-landeira e @lhsazevedo .

Questões como essa tem aparecido de quanto em quando, e por conta disso acrescentei um [wiki a respeito](https://github.com/php/doc-pt_br/wiki/Perguntas-e-issues-frequentes#encontrei-um-arquivo-desatualizado-parcialmente-traduzido-ou-errado).

Como é uma questão já mapeada, daí já é para fechar o issue imediatamente.
