### ISSUE TITLE
Arquivamento de arquivos abandonados na tradução

### ISSUE THREAD

**Issue by alfsb** [php/doc-pt_br#270]
Olá. Estamos muito perto de conseguir atualizar a parte do `language/` do manual. Faltam só uns poucos arquivos desatualizados, quais eu pretendo atacar na sequência. Um motivo a comemorar, ter essa parte do manual bem atualizada.

Porém, daí, sobra todo o resto do manual, que continua enorme, com pedaços da tradução já muito obsoletos, de partes que foram traduzidas e nunca atualizadas. Aqui há basicamente três caminhos:

1. Atualizar esses arquivos;
2. Remover esses arquivos;
3. Deixar as coisas como estão.

Eu não pretendo ir pelo (3), para não correr o risco da tradução pt_BR ser novamente considerada abandonada, assim como acho impossível cumprir com o (1) para todo o manual.

O que eu pretendo fazer agora é:

1. Atualizar os arquivos sob meu `maintainer` com **pequenas** alterações;
2. Renomear os demais arquivos sob meu `maintainer` de `.xml` para `.old`.

Esse renomear tem o mesmo efeito de efetivamente apagar o arquivo no que concerne à tradução: remove do rastreamento do `revcheck.php`, e remove o arquivo da compilação do manual. Mas não some com o histórico totalmente, que seria um enorme problema da alternativa de apagar o arquivo do controle de versão.

Essa é a forma que eu encontrei para lidar com os meus próprios arquivos abandonados. Vou seguir por essa linha, para todos os arquivos sob o meu `maintainer`. Mas não vou parar aí. Depois, eu provavelmente vou seguir a mesma linha para arquivos de outros `maintainer`s, atualizando pequenas traduções e remover/renomear os arquivos com grandes alterações. Por fim, os arquivos sem revtag serão todos renomeados/removidos, já que esses nem dá para saber o tamanho da alteração.

Bem imagino que esse issue vai soar bem triste, e possivelmente polêmico, e por isso mesmo que estou abrindo para comentários, e assim como sugestões de alternativas.

Eu estou abrindo também a discussão da definição de um **corte objetivo do que é considerado arquivo ou issue abandonado.** Eu tenho usado informalmente o prazo de 3 meses, mas gostaria de ouvir comentários disso também.

**Comment by adielcristo** [comment]
Parabéns a todas as pessoas envolvidas, realmente esse é um grande feito. 🥳
@alfsb Acho esse planejamento plausível e dentro do nosso ritmo de atualizações. Vou adicionar o que estou fazendo no momento:

1. Estou atualizando as outras seções além da `reference` dando prioridade à seção `language`, por tratarem de assuntos amplos, englobando o uso do PHP como um todo. Deixei a `reference` por último na lista de prioridades por se tratar da documentação de extensões e recursos específicos. Ainda assim, fico tentado a traduzir seções da `reference` nas quais tenho interesse no momento. Ainda estou avaliando isso, mas provavelmente vou pegar algumas delas para manter nos próximos dias.
2. Nas seções estou seguindo as listas disponibilizadas pelo [`revcheck`](http://doc.php.net/revcheck.php?p=files&lang=pt_br). Foi daí que tirei as últimas issues criadas, incluindo a #259. Pensei em criar issues para todas as seções, mas pisei no freio e optei por criar apenas algumas issues para as traduções mais imediatas e ir criando mais à medida que o processo for evoluindo. Também estou aproveitando esse processo para revisar os outros arquivos de cada seção. Por isso eles estão listados nas issues.
3. Ao revisar ou traduzir os arquivos, se não houver um `maintainer`, estou assumindo a manutenção do arquivo. Caso haja um `maintainer` mas o arquivo esteja sem atualização há muito tempo ou no caso das modificações feitas por mim serem muito extensas, também estou assumindo a manutenção.
4. Estou tentando tornar essas tarefas recorrentes no longo prazo e, à medida que as realizo, estou revisando todo o processo de tradução e tomando nota de pontos que possam ser melhorados ou automatizados.

Esses passos são apenas uma guia, e podem não ser seguidos à risca. Além disso, ainda não consegui chegar no nível de disciplina e organização que almejo, então acontece de eu sumir por um tempo com as contribuições. As issues são uma forma de me organizar nesse processo e não me perder nas atividades.

Com relação ao seu planejamento, eventualmente chegarei nos arquivos desatualizados mas vai demorar para a maioria deles, então fique à vontade para seguir com as alterações.

**Comment by alfsb** [comment]
Como estamos só nós dois mexendo com mais frequência, acho que dá para ir por aí mesmo. Peço continuar abrindo os issues para os arquivos ou diretórios que planejar mexer, que daí esses eu evito.

Sobre o ritmo, bem sei como é, e o que eu faço aqui é incluir o resultado local do `revcheck.php` numa lista de abas que eu abro diariamente. Isso acaba virando um auto incentivo.

Já comecei a pegar os arquivos com micro atualizações para progredir, ver em qual ritmo que sai. Mas é possível que logo sobrem só os arquivos com alterações médias a grandes, e daí vou começar a aplicar o critério para arquivamento de traduções antigas e abandonadas.

**Comment by alfsb** [comment]
Depois desse issue aberto, as coisas tem andado até bem. Mais pessoas contribuindo, ainda que esporadicamente. E sem sugestões outras na questão de maintainer ou issues abandonados, eu vou começar a implementar isso na prática.

@adielcristo , sobre o que comentou de abrir issues para todas as seções, realmente não é por ai. O `revcheck` e o wiki/Situação atual já são um grande TODO, abrir issues em cima dele só duplica a informação. Além disso, issues são algo tradados como reservas, de forma que Issues abertos acabam tendo o efeito inverso sobre a tradução, de bloquear a atualização de arquivos.

Já na próxima semana eu vou começar a fechar os issues sem movimentos a mais de 3 meses.

Terminando os arquivos meu maintainer com pequenas alterações, vou efetivar o abandono (rename) de alguns arquivos meus com grandes alterações, e na sequência vou começar a dar o mesmo tratamento aos arquivos de outros maintainer, culminando com o mass rename de todos os arquivos sem revtag.

**Comment by adielcristo** [comment]
@alfsb Não pensei na possibilidade das issues serem tratadas como reserva. Vou fechar as issues relacionadas às pastas e manter apenas a que estou trabalhando atualmente. A finalidade delas era para ajudar no meu planejamento das atividades, mas estou vendo fluxos alternativos envolvendo apenas as PRs para traduções rápidas e branches para traduções mais demoradas.

**Comment by alfsb** [comment]
Sim, em especial para fluxos alternativos. Há tradutores frequentes, há tradutores infrequentes. Há traduções rápidas, há processos longos e passo a passo. Infelizmente não tem como tratar de uma forma só.

Mas veja. Planejamento -> organização -> reserva. Ainda mais nos arquivos "de cima" no revcheck, principalmente os no `language/`. A reserva que vira tradução em semanas é feliz. A reserva que fica meses bloqueando de outra pessoa de se organizar de mexer nos arquivos ou pastas apartados é triste.

Nem é a primeira vez que isso ocorre na tradução aqui, nessa última década e meia. A ideia de oficializar a regra é de principalmente evitar o caso da reserva que passam meses (ou anos) sem progressos.

**Comment by lhsazevedo** [comment]
Chegando um pouco atrasado, mas acho ótima a ideia de arquivar os arquivos desatualizados. Observei que eu mesmo estou evitando a versão traduzida do manual por conta das informações erradas. Seria até uma funcionalidade interessante de se ter direto no PHD no futuro.

**Comment by alfsb** [comment]
Esse é uma direção qual eu vou levar o manual do PHP, sim. Ele ter um tamanho que dá para manter, em vez de manter um monte de arquivos efetivamente abandonados. Eu resisti de apagar completamente o manual para recomeçar, mas esse não deixa de ser um meio termo.

Passos para isso acontecer é colocar uma coluna `days` no revcheck, e com base nessa estatística, ir renomeando os arquivos muito antigos.

Os arquivos sem nem hash correto vão acabar sendo renomeados em massa, já que não dá para tirar nem diff deles.

**Comment by alfsb** [comment]
Consegui emplacar a coluna `Days` no revcheck local. A coluna vai ser a base de novos direcionamento de esforços de tradução *e abandono* de arquivos, agora que volta a ser possível identificar os arquivos muito desatualizados.

Eu ainda vou focar esforços nas prioridades (`language/` e afins), mas logo vou começar a renomear os arquivos sem revtag, e depois os arquivos grandes muito antigos, em um esforço geral de deixar o manual do PHP num tamanho que seja possível de manter atualizado.

**Comment by alfsb** [comment]
Oficializando a política dos 90 dias, com a informação espalhada pelo wiki: https://github.com/search?q=repo%3Aphp%2Fdoc-pt_br+90&type=wikis
