### ISSUE TITLE
Erro ortográfico

### ISSUE THREAD

**Issue by Jhony2002** [php/doc-pt_br#287]
From manual page: https://php.net/security.variables

---Ele pode ser usado in conjunto com outros scripts de maneira negativa?

O certo seria ortograficamente falando seria "Ele pode ser usado em conjunto com outros scripts de maneira negativa?"

**Comment by alfsb** [comment]
Obrigado pelo aviso, corrigido. Aproveitei para passar um corretor automático, que pegou ainda outro erro. Em poucos dias aparece nos sites a correção.
