### ISSUE TITLE
Erro ortográfico

### ISSUE THREAD

**Issue by Jhony2002** [php/doc-pt_br#291]
From manual page: https://php.net/security.apache

---"Por exemplo, se você estiver usando o PHP para acessar um banco de dados, a menos que o banco de dados tenha um controle de acesso interno, você terá que faz o banco de dados acessível ao usuário "nobody""

Erro 1 - Parágrafo 1, segunda frase. o termo você terá que "faz" está incorreto e a não inclusão da palavra "seja" após a palavra "dados", o correto seria você terá que fazer e a inclusão do "seja "ou melhor ainda "você terá que fazer com que o banco de dados seja acessível ao usuário "nobody"".

Erro 2- Frequência perdeu a crase.

Erro 3-"Um erro freqüente de segurança feito até esse ponto é **permiter** ao apache permissões de administrador (root), ou aumentar as habilidades do apahce de qualquer outra forma" . Nesta frase, o correto seria 'permitir'

Erro 4-  "Você também pode configurar area exclusivas para o Apache, restringir todas as atividades web para arquivo que não sejam de algum usuário ou do sistema.". Área sem o acento.

**Comment by alfsb** [comment]
Obrigado pelas correções. Encaminhadas. Demora um pouco para aparecer no visual. Mas se gostou de ajudar com correções, de uma olhada no wiki, para ver como você mesmo consegue encaminhar essas e outras correções de forma mais direta :)
