### ISSUE TITLE
Dificuldade em pegar o hash

### ISSUE THREAD

**Issue by willian-rosa** [php/doc-pt_br#294]
Boa noite, 

Estou traduzindo o arquivo `reference/array/functions/key.xml`  no entanto no arquivo `revcheck.html` está retornando o Warn: No hash for en/reference/array/functions/key.xml.

Estou rodando os seguintes comando para gerar os revcheck.html:
```
php doc-base/configure.php --with-lang=pt_BR --enable-xml-details 
php phd/render.php --docbook doc-base/.manual.xml --package PHP --format php --lang=pt_BR 
php doc-base/scripts/revcheck.php pt_BR > revcheck.html

xdg-open revcheck.html
```
Todos os projetos (doc-base, phd, en, pt_BR/) estão atualizados.

E ai não tem o hash do arquivo:
![image](https://github.com/php/doc-pt_br/assets/17603785/95f44baa-26d7-4528-9f9c-0efd19808790)

O que estou fazendo de errado?

**Comment by alfsb** [comment]
Reexecutei aqui, e não consegui reproduzir.
```
php -v
PHP 8.1.2-1ubuntu2.13 (cli) (built: Jun 28 2023 14:01:49) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2-1ubuntu2.13, Copyright (c), by Zend Technologies
```

Qual a versão do PHP que está usando ai?

Esse `Warn:` é único no `revcheck.php`, e acontece quando não acha uma chave no array global `$gitData`. Então... é provavelmente um problema nessa função em particular.

Se souber programar em PHP, comece por aí. Senão, avise para tentar orientar em como colocar um debug print para determinar o que acontece diferente no seu caso.

Essa função basicamente tira um `git --no-pager log --name-only` do diretório `en/` e processa. Então pode ser alguma diferença na saída desse comando. As primeiras linhas desse comando, aqui:
```
$ cd en/
$ git --no-pager log --name-only | head -n 200
commit 58be32a1d40bde870bfd2f8bd82d36938149d09d
Author: Remi Collet <remi@php.net>
Date:   Thu Jul 6 11:45:38 2023 +0200

    new constants with librpm 4.19

reference/rpminfo/constants.xml

commit 6b56e6f444e49396ee5122258ee85b99a8543f6a
Author: LionelMallet <34163543+lionelmalletpro@users.noreply.github.com>
Date:   Tue Jul 4 22:00:40 2023 +0200

    Improve the refpurpose of array_count_values() (#2558)

reference/array/functions/array-count-values.xml

commit 96a8379cd86b3ca4f1f5b2b94c5fb263f38050fd
Author: Máté Kocsis <kocsismate@woohoolabs.com>
Date:   Tue Jul 4 21:35:33 2023 +0200

    Render interfaces according to the new PhD format (#2556)
    
    According to https://github.com/php/phd/pull/75

language/predefined/arrayaccess.xml
language/predefined/backedenum.xml

```

**Comment by alfsb** [comment]
Ah sim, esqueci de comentar, no wiki Situação atual, tem uma ferramenta online que permite pegar hash dos arquivos desatualizados ou não traduzidos. É um paliativo, para você não ficar travado, enquanto debugamos esse problema ai: https://github.com/php/doc-pt_br/wiki/Situa%C3%A7%C3%A3o-atual
