### ISSUE TITLE
Diferenças estruturais nos arquivos traduzidos, atributos

### ISSUE THREAD

**Issue by alfsb** [php/doc-pt_br#298]
Eu estou desenvolvendo algumas ferramentas para melhoria do manual, e hoje a primeira começou a funcionar. Um verificador que detecta diferenças de tag/atributos/valor, entre original e tradução. Tem mais ferramentas que eu pretendo adicionar, porém na primeira já surgiu uma listagem de alertas. Daí que pretendo zerar os alertas antes de ir para a próxima ferramenta e assim por diante.

Porém esses alertas surgem em arquivos que estão atualizados, ao menos em teoria, Podem representar pequenos erros de digitação a alguns pedaços a mais ou a menos. Como são coisas simples, eu estou oferecendo a quem quiser iniciar na tradução, ou que esteja buscando alguma coisa rápida para fazer.

Para evitar duplicação, podem solicitar reservas de uma semana nos arquivos.

```
qaxml.a.check: en/appendices/filters.xml pt_BR/appendices/filters.xml

+ link linkend ref.bzip2

qaxml.a.check: en/appendices/migration81/new-features.xml pt_BR/appendices/migration81/new-features.xml

+ link linkend language.fibers
- link linkend class.fiber

qaxml.a.check: en/install/unix/index.xml pt_BR/install/unix/index.xml

+ link linkend configure.about
- link linkend configure

qaxml.a.check: en/language/functions.xml pt_BR/language/functions.xml

+ link linkend language.oop5.basic.nullsafe

qaxml.a.check: en/language/predefined/variables/session.xml pt_BR/language/predefined/variables/session.xml

- phpdoc:varentry role noversion

qaxml.a.check: en/language/predefined/variables/superglobals.xml pt_BR/language/predefined/variables/superglobals.xml

- refsect1 role changelog
- tgroup cols 2

qaxml.a.check: en/language/predefined/variables/request.xml pt_BR/language/predefined/variables/request.xml

- phpdoc:varentry role noversion

qaxml.a.check: en/language/predefined/variables/phperrormsg.xml pt_BR/language/predefined/variables/phperrormsg.xml

- phpdoc:varentry role noversion
- link linkend function.set-error-handler

qaxml.a.check: en/language/predefined/variables/get.xml pt_BR/language/predefined/variables/get.xml

- phpdoc:varentry role noversion

qaxml.a.check: en/reference/apache/functions/apache-request-headers.xml pt_BR/reference/apache/functions/apache-request-headers.xml

- type class union

qaxml.a.check: en/reference/array/functions/array-fill.xml pt_BR/reference/array/functions/array-fill.xml

+ link linkend function.array-fill.example.negative-start-index
- link linkend function.array-fill.example.basic

qaxml.a.check: en/reference/array/functions/current.xml pt_BR/reference/array/functions/current.xml

+ type class union
- parameter role reference

qaxml.a.check: en/reference/array/functions/array-search.xml pt_BR/reference/array/functions/array-search.xml

- refsect1 role changelog
- tgroup cols 2

qaxml.a.check: en/reference/array/functions/array-sum.xml pt_BR/reference/array/functions/array-sum.xml

- screen role php

qaxml.a.check: en/reference/array/functions/extract.xml pt_BR/reference/array/functions/extract.xml

+ parameter role reference

qaxml.a.check: en/reference/filter/constants.xml pt_BR/reference/filter/constants.xml

+ varlistentry xml:id constant.input-cookie
- varlistentry xml:id constant.input-cookies

```

**Comment by alfsb** [comment]
Reservando `reference/filter/constants.xml`.

Aliás, eu vou pegar casos de baixo para cima, caso alguém queira pegar os casos de cima para baixo, sem reservar, só indo fazendo, e nos encontramos no meio.

**Comment by alfsb** [comment]
Resolvido o anterior, reservado `reference/array/functions/extract.xml`.

**Comment by alfsb** [comment]
Resolvido o anterior. O próximo que eu pegaria, `reference/array/functions/array-sum.xml`, é extremamente simples. Acredito que outros casos podem ser bem simples também.

Deixando esse issue aberto por um tempo, como um issue simples para começar. Mas no provável caso que não aconteça, daí esses experimentos com issues param, movendo o assunto "começo simples aqui" para uma seção fixa no wiki.

**Comment by alfsb** [comment]
Reservando o issue para mim, e assim zerar esses alertas de QA antes de ir para o próximo.

**Comment by alfsb** [comment]
Diferenças reportados na inicial do issue resolvidos. Yay. Mas apareceu um novo, que vai exigir um pouco de trabalho por se tratar de alteração que quebra o manual. Vou deixar o issue aberto até resolver, enquanto atualizo os arquivos em cascata para tirar essa diferença:
```
qaxml.a.check: en/reference/info/ini.xml pt_BR/reference/info/ini.xml

- varlistentry xml:id ini.magic-quotes-gpc
- varlistentry xml:id ini.magic-quotes-runtime
```
Tem uns sete arquivos que referenciam diretamente variações de `ini.magic-quotes` que precisarão ser alterados antes de poder tirar essa definições hoje vazias de info/ini.xml.

**Comment by lhsazevedo** [comment]
Que ferramenta incrível!

**Comment by alfsb** [comment]
> Que ferramenta incrível!

Né? Ela consegue apontar diferenças estruturais que são difíceis de detectar por inspeção visual. Essa é a primeira. Eu pretendo fazer mais umas três, para lidar com outras questões estruturais ou de tradução.

**Comment by alfsb** [comment]
E... resolvido. Próxima parada, ferramenta de detecção diferenças de entidades e processing instructions desatualizados!

**Comment by alfsb** [comment]
Isso é mais a título de curiosidade, já que eu mesmo vou pegar esses casos para resolver, mas...

**Diferenças estruturais nos arquivos traduzidos, entities**
```
qaxml.e: pt_BR/appendices/about.xml

+ return.falseforfailure

qaxml.e: pt_BR/appendices/migration70/incompatible/other.xml

+ example.outputs.56

qaxml.e: pt_BR/faq/mailinglist.xml

* url.php.mailing-lists -1 +3 
* url.php.support -3 +1 

qaxml.e: pt_BR/language/generators.xml

* yield -1 +3 

qaxml.e: pt_BR/language/exceptions.xml

* throw -2 +3 

qaxml.e: pt_BR/language/oop5/basic.xml

* null -3 +2 

qaxml.e: pt_BR/language/predefined/unhandledmatcherror.xml

* match -1 +2 

qaxml.e: pt_BR/language/types/float.xml

+ true

qaxml.e: pt_BR/language/types/array.xml

* false -2 +3 
* null -5 +6 

qaxml.e: pt_BR/reference/array/functions/reset.xml

* false -4 +3 

qaxml.e: pt_BR/reference/ctype/book.xml

- Functions

qaxml.e: pt_BR/reference/datetime/functions/timezone-open.xml

+ Alias

qaxml.e: pt_BR/reference/funchand/reference.xml

* Functions -2 +1 

qaxml.e: pt_BR/reference/gmp/reference.xml

+ Functions

qaxml.e: pt_BR/reference/json/functions/json-encode.xml

+ resource

qaxml.e: pt_BR/reference/memcached/memcached/addbykey.xml

- true
- false
+ return.success

qaxml.e: pt_BR/reference/memcached/memcached/decrement.xml

- false
+ return.falseforfailure

qaxml.e: pt_BR/reference/memcached/memcached/casbykey.xml

- true
- false
+ return.success

qaxml.e: pt_BR/reference/memcached/memcached/ispristine.xml

- true
- false

qaxml.e: pt_BR/reference/memcached/memcached/append.xml

- true
- false
+ return.success

qaxml.e: pt_BR/reference/memcached/memcached/decrementbykey.xml

- false
+ return.falseforfailure

qaxml.e: pt_BR/reference/memcached/memcached/add.xml

- true
- false
+ return.success

qaxml.e: pt_BR/reference/memcached/memcached/appendbykey.xml

- true
- false
+ return.success

qaxml.e: pt_BR/reference/memcached/memcached/cas.xml

- true
- false
+ return.success

qaxml.e: pt_BR/reference/memcached/memcached/deletebykey.xml

- false
+ return.success

qaxml.e: pt_BR/reference/memcached/memcached/delete.xml

- false
+ return.success

qaxml.e: pt_BR/reference/memcached/memcached/ispersistent.xml

- true
- false

qaxml.e: pt_BR/reference/mhash/setup.xml

* url.mhash -2 +1 

qaxml.e: pt_BR/reference/mysqli/mysqli/execute-query.xml

* array -1 +2 

qaxml.e: pt_BR/reference/opcache/functions/opcache-compile-file.xml

- false
+ return.falseforfailure

qaxml.e: pt_BR/reference/opcache/functions/opcache-get-status.xml

- false
+ return.falseforfailure

qaxml.e: pt_BR/reference/pdo/configure.xml

* php.ini -3 +2 
```
Caso alguém reconheça um arquivo sob seu maintainer que queira mexer. Nesse caso eu vou de cima para baixo, caso alguém queira pegar de baixo para cima, só avisar.

**Comment by lhsazevedo** [comment]
Tenho interesse em acompanhar/contribuir sim. Vale a pena criar a issue,

**Comment by alfsb** [comment]
Blz. Vou ver com qual velocidade vai andar. Por enquanto está andando bem rápido. Mas enquanto não abro o issue, dá para ir acompanhando rodando isso daqui:
```
php doc-base/scripts/translation/configure.php pt_BR
php doc-base/scripts/translation/qaxml.a.php
php doc-base/scripts/translation/qaxml.e.php
php doc-base/scripts/translation/qaxml.p.php
#php doc-base/scripts/translation/qaxml.t.php

php doc-base/scripts/translation/qaxml.t.php acronym
php doc-base/scripts/translation/qaxml.t.php classname
php doc-base/scripts/translation/qaxml.t.php constant
php doc-base/scripts/translation/qaxml.t.php envar
php doc-base/scripts/translation/qaxml.t.php function
php doc-base/scripts/translation/qaxml.t.php interfacename

php doc-base/scripts/translation/qaxml.t.php parameter
php doc-base/scripts/translation/qaxml.t.php type
php doc-base/scripts/translation/qaxml.t.php classsynopsis
php doc-base/scripts/translation/qaxml.t.php constructorsynopsis
php doc-base/scripts/translation/qaxml.t.php destructorsynopsis
php doc-base/scripts/translation/qaxml.t.php fieldsynopsis
php doc-base/scripts/translation/qaxml.t.php funcsynopsis
php doc-base/scripts/translation/qaxml.t.php methodsynopsis

php doc-base/scripts/translation/qaxml.t.php code
php doc-base/scripts/translation/qaxml.t.php filename
php doc-base/scripts/translation/qaxml.t.php literal
php doc-base/scripts/translation/qaxml.t.php varname

php doc-base/scripts/translation/qaxml.t.php
```

usando como `doc-base` um checkout desse fork aqui: https://github.com/alfsb/doc-base

Vai gerar trocentos alertas... São os alertas que eu estou trabalhando esse mês.

**Comment by alfsb** [comment]
A listagem de `php doc-base/scripts/translation/qaxml.t.php`, em particular, é o mais direto de resolver.

Representa diferenças estruturais entre os arquivos, no nível de tag.

**Comment by alfsb** [comment]
Terminei todas as principais alterações estruturais. Sobrou coisas que, espero, não causem quebras no manual, mas que vou continuar corrigindo até chegar no ponto de consistência máxima. Depois disso é atacar os arquivos de prioridade máxima, depois disso é dar uma boa mexida no wiki e depois disso... começam as machadas massificas em arquivos muito antigos.

Em paralelo com a remoção massificada de traduções muito antigas, eu vou abrir um issue permanente de "casos simples para iniciantes", focando em arquivos pequenos ou com pequenas alterações.

O casos se diferenças estruturais que sobraram meio que se enquadram nisso, mas para não "poluir" o issue de iniciantes / casos fáceis, eu vou evitar incluir essas diferenças estruturais residuais porque elas precisam de ferramental muito específico, como descrito logo acima.

Tem uns ~400 alertas de rodar:
```
php doc-base/scripts/translation/qaxml.t.php literal
php doc-base/scripts/translation/qaxml.t.php
```

É nesses casos que vou concentrar os próximos dias/semanas. Se alguém quiser contribuir, eu vou pegar os casos de `<literal>`, daí pediria para se concentrarem nas demais tags dectectadas.

**Comment by alfsb** [comment]
É isso aí pessoal. Diferenças estruturais nos arquivos traduzidos minimizadas. Vai começar a rolar mass delete em arquivos muito antigos, assim como está liberado tomar para si o maintainer de quaisquer arquivos com days > 90.

Para facilitar isso, eu vou tentar encaminhar alterações no revcheck, acrescentando essa informação.

Tem as novas (prioridades)[https://github.com/php/doc-pt_br/wiki/Prioridades], que é interessante seguir, mas como o objetivo geral é minimizar o tamanho do revcheck em si, podem focar nos arquivos menores, em tamanho ou em alteração, que gera o maior progresso com o menor esforço.
