### ISSUE TITLE
intl installation

### ISSUE THREAD

**Issue by leandroleonard** [php/doc-pt_br#310]
From manual page: https://php.net/intl.configuration

--- intl does't work in mac os

**Comment by alfsb** [comment]
Olá @leandroleonard . Esse repositório é da tradução do manual, que basicamente segue os originais em inglês. Os problemas de documentação precisam ser abertos no repositório de origem: https://github.com/php/doc-en

Quando for abrir o issue lá, é bom dar mais alguns detalhes. O que tentou, onde, o que esperava que acontecesse e se apareceu alguma mensagem de erro.
/
