### ISSUE TITLE
Coordenação 2023

### ISSUE THREAD

**Issue by alfsb** [php/doc-pt_br#365]
Para diminuir duplicidades de esforços, peço que deem um toque aqui antes de começar um dia de tradução, indicando quais arquivos ou pastas pretendem trabalhar no dia. Não precisa ser nada muito elaborado. Reservas valem por 2 semanas. Passou disso, ou enviou as alterações, daí vou tentar apagar as postagens, para que o issue não cresça desorganizado.

A prioridade de processamento setá temporal. Terá o PR preferido quem fizer a reserva ou enviar o PR primeiro, e terá o PR preterido quem enviar PR em cima de arquivo/diretório reservado nesse issue.

Provavelmente vou conseguir fazer cherry-pick de PR, que o GitHub criou umas ferramentas novas disso, e assim evitar recusar um PR inteiro numa situação de conflito.

Aberto para comentários.

E aberto também de continuar mandando PRs sem fazer reserva, apenas aplicado-se as preferências/preterências acima de agora em diante. Eu bem sei o quanto isso é inconveniente, mas é o jeito de manter o serviço leve. O risco de se perder trabalhos por duplicidade continua existindo indo por esse caminho, então não muda muita coisa da situação atual.

**Comment by leonardolara** [comment]
Boa iniciativa.
Estou trabalhando nos arquivos de reference/filesystem (faltantes, desatualizados e abandonados).

**Comment by fernandowobeto** [comment]
Bom dia!
WIP: reference/filesystem/functions/copy.xml

**Comment by leonardolara** [comment]
> Boa iniciativa. Estou trabalhando nos arquivos de reference/filesystem (faltantes, desatualizados e abandonados).

PR enviado.

**Comment by leonardolara** [comment]
WIP: reference/var/*

**Comment by fernandowobeto** [comment]
Boa tarde!
WIP: reference/spl/arrayiterator/*

**Comment by leonardolara** [comment]
WIP: reference/strings/* e reference/strings/functions/*

**Comment by fernandowobeto** [comment]
Boa tarde!
WIP: reference/spl/arrayobject/*

**Comment by fernandowobeto** [comment]
Boa tarde!
WIP: reference/spl/directoryiterator/*

**Comment by alfsb** [comment]
Primeira limpada de avisos concluídos, até para ver como fica. Gera um pouco de ruído por conta dos avisos de deleção (gera email?), mas na ordem de leitura fica bom.

Não tinha pensando nisso, mas a história de modificar a própria mensagem, avisando que concluiu, foi uma ideia muito boa! Facilita demais, até por gerar menos leituras separadas.

**Comment by fernandowobeto** [comment]
Boa tarde!
WIP: reference/spl/filteriterator/*

**Comment by fernandowobeto** [comment]
Bom dia!
WIP: reference/spl/functions/*

**Comment by fernandowobeto** [comment]
Bom dia!
WIP: reference/spl/parentiterator

**Comment by fernandowobeto** [comment]
Boa noite!
WIP: reference/spl/recursivecachingiterator/*

**Comment by fernandowobeto** [comment]
Boa noite!
WIP: reference/spl/recursivedirectoryiterator/*

**Comment by leonardolara** [comment]
Bom dia!
WIP: arquivos desatualizados de
reference/dbase/*
reference/dom/*
reference/stream/*
reference/strings/functions/*

Concluído. PR enviado.

**Comment by leonardolara** [comment]
Bom dia!
WIP: arquivos desatualizados de
reference/exec/*
reference/exif/*
reference/errorfunc/*

Concluído. PR enviado.

**Comment by leonardolara** [comment]
Bom dia!
WIP: arquivos desatualizados de
reference/filter/*
reference/fpm/*
reference/ftp/*
reference/funchand/*

**Comment by fernandowobeto** [comment]
Boa tarde!
WIP: reference/spl/recursiveiteratoriterator/*

**Comment by fernandowobeto** [comment]
Boa tarde!
WIP: reference/tcpwrap/*

**Comment by fernandowobeto** [comment]
Boa noite!
WIP: reference/tidy/*

**Comment by fernandowobeto** [comment]
Boa noite!
WIP: reference/tokenizer

**Comment by fernandowobeto** [comment]
Bom dia!
WIP: reference/tokenizer/functions/*

**Comment by fernandowobeto** [comment]
Bom dia!
WIP: reference/uodbc/*

**Comment by leonardolara** [comment]
Bom dia!
WIP:
reference/gettext/*
reference/gmp/*

**Comment by fernandowobeto** [comment]
Boa tarde!
WIP: reference/uodbc/functions/*

**Comment by fernandowobeto** [comment]
Bom dia!
WIP: reference/url/*

**Comment by fernandowobeto** [comment]
Boa noite!
WIP: reference/url/functions/*

**Comment by leonardolara** [comment]
Bom dia!
WIP:
reference/json/*
reference/libxml/*
reference/lua/*
reference/lzf/*

**Comment by fernandowobeto** [comment]
Boa tarde!
WIP: reference/simplexml/simplexmlelement/*

**Comment by fernandowobeto** [comment]
Boa noite!
WIP: reference/snmp/*

**Comment by fernandowobeto** [comment]
Boa noite!
WIP: reference/sockets/*

**Comment by leonardolara** [comment]
Bom dia!
WIP:
reference/memcached/*
reference/mhash/*
reference/misc/*

**Comment by fernandowobeto** [comment]
Bom dia!
WIP: reference/session/functions/*

**Comment by fernandowobeto** [comment]
Boa tarde!
WIP: reference/wddx/functions/*

**Comment by fernandowobeto** [comment]
Boa tarde!
WIP: reference/xattr/*

**Comment by fernandowobeto** [comment]
Boa noite!
WIP: reference/xsl/*

**Comment by fernandowobeto** [comment]
Boa noite!
WIP: reference/reflection/*

**Comment by fernandowobeto** [comment]
Boa noite!
WIP: reference/readline/*

**Comment by fernandowobeto** [comment]
Boa noite!
WIP: reference/opcache/*

**Comment by fernandowobeto** [comment]
Boa noite!
WIP: language/oop5/*

**Comment by leonardolara** [comment]
Bom dia!
WIP: 
reference/pgsql/*
reference/session/*

**Comment by leonardolara** [comment]
WIP:
reference/shmop/*
reference/sockets/*
reference/wddx/*

**Comment by fernandowobeto** [comment]
Boa tarde!
WIP: reference/readline/functions/*

**Comment by fernandowobeto** [comment]
Boa tarde!
WIP: reference/reflection/reflectionextension/*

**Comment by fernandowobeto** [comment]
Boa tarde!
WIP: reference/reflection/reflectionnamedtype/*

**Comment by leonardolara** [comment]
Boa noite!
WIP: reference/xsl/xsltprocessor/*

**Comment by fernandowobeto** [comment]
Bom dia!
WIP: reference/session/*

**Comment by fernandowobeto** [comment]
Bom dia!
WIP: reference/session/functions/*

**Comment by fernandowobeto** [comment]
Boa noite!
WIP: reference/session/sessionidinterface/*

**Comment by fernandowobeto** [comment]
Boa noite!
WIP: reference/session/sessionupdatetimestamphandlerinterface/*

**Comment by fernandowobeto** [comment]
Bom dia!
WIP: reference/dom/*

**Comment by fernandowobeto** [comment]
Boa tarde!
WIP: reference/dom/*

**Comment by fernandowobeto** [comment]
Bom dia!
WIP: reference/dio/functions/*

**Comment by fernandowobeto** [comment]
Boa noite!
WIP: reference/dio/*

**Comment by fernandowobeto** [comment]
Boa tarde!
WIP: reference/dom/domattr/*

**Comment by fernandowobeto** [comment]
Boa noite!
WIP: reference/dom/domcdatasection/*

**Comment by fernandowobeto** [comment]
Boa noite!
WIP: reference/dom/domcharacterdata/*

**Comment by fernandowobeto** [comment]
Boa noite!
WIP: reference/dom/domchildnode/*

**Comment by fernandowobeto** [comment]
Boa noite!
WIP: reference/dom/domcomment/*

**Comment by fernandowobeto** [comment]
Boa noite!
WIP: reference/dom/domdocument/*

**Comment by fernandowobeto** [comment]
Boa noite!
WIP: reference/dom/domdocumentfragment/*

**Comment by fernandowobeto** [comment]
Bom dia!
WIP: reference/dom/domelement/*

**Comment by alfsb** [comment]
WIP: reference/pdo/pdo
WIP: reference/pdo/pdostatement
WIP: reference/pgsql

Basicamente os poucos arquivos desatualizados.

**Comment by alfsb** [comment]
Aproveitando, abrindo a discussão de algumas frentes nesse issue, que tende a ser fechado e/ou renomeado após a virada do ano. Considero que foi um sucesso. E ao mesmo tempo gostaria de ouvir comentários a respeito dos seguintes direcionamentos.

1. Fechar e abrir um issue por ano. Meio que isso já está implícito no título do issue, e a principal razão disso é o acúmulo de mensagens apagadas, que só gera navegação sem nada acrescentar. Ou manter por tempo indeterminado?
2. No issue apenas indicar reserva, e no PR indicar continuidade/finalização.

O (2) funcionaria assim: em vez de ter de voltar no issue de coordenação e editar a própria reserva como finalizada, isso é feito no PR. Avisando por mensagem que ainda se pretende complementar/alterar *ou* alterando o PR para um estado de Draft. Ao finalizar, tira-se o status de Draft, o que libera os editores de revisar e mesclar.

Já o (1) é função de algo que até já tinha percebido de antes, mas que faltou *comemoração*. A tradução do manual pt_BR sem nenhum arquivo desatualizado! Isso quase nunca aconteceu na (longa) história da tradução brasileira. E é fruto, claro, do enorme esforço de tradução que ocorreu nesse ano. Esforço esse que gerou esse tanto de reservas, que deixou o issue longo. E que insisto, é algo a comemorar!

Já o issue do doc-base, para oficializar os scripts de QA sync andou, mas não muito. Esse ainda é o meu foco/roadblock, antes de pegar alguma outra grande condução no manual. Mas passando isso, daí abre espaço técnico para tentar algumas translations fest no 2024.

**Comment by fernandowobeto** [comment]
Bom dia!
1) Concordo, acredito até que uma issue por ano ainda assim ficará longa com as mensagens deletadas, visto que a atual já foi criada perto do final deste ano.
2) Para mim tanto faz, sempre que concluo uma tradução no final das contas já vou na issue mesmo, pois já crio outra com WIP. Mas se para vocês, como revisores e "mergeadores" fica melhor essa abordagem da mensagem no commit, tranquilo, apenas criamos um padrão e seguimos.

**Comment by alfsb** [comment]
> 2. Para mim tanto faz, sempre que concluo uma tradução no final das contas já vou na issue mesmo, pois já crio outra com WIP. Mas se para vocês, como revisores e "mergeadores" fica melhor essa abordagem da mensagem no commit, tranquilo, apenas criamos um padrão e seguimos.

A mensagem no PR é talvez acessória, mais relevante mesmo acho que é o status Draft/Ready. Para evitar essas falhas do lado de quem faz merge de mesclar PRs que ainda serão modificados.

Na verdade, o problema surge por conta dessa informação ter ficado separada em duas telas. O PR já tem a funcionalidade Draft/Ready, e o aviso de conclusão no issue de coordenação acabou duplicando isso. Daí quem olha a tela de PR isoladamente não percebe que tem gente trabalhando ainda no WIP reservado.

Daí no próximo issue de coordenação eu pensei de padronizar e instruir que no issue fica reservas, e no PR mudar para Draft caso vá querer mexer depois. Assim a informação de merge/não merge fica em uma mesma tela, evitando de um editor fazer o merge em um PR ainda inconcluso.

O objetivo da alteração é tentar evitar de um editor de quebrar a rotina de um tradutor. Principalmente isso.

Não ficaria proibido de continuar informando no issue de coordenação as conclusões caso se queira. O issue de coordenação é, afinal, para discutir e comunicar os assuntos de coordenação.

Esse primeiro issue foi aberto meio às pressas, quase como um experimento. E que mesmo assim deu um bom resultado. Acho que com essas mexidas já dá para padronizar isso nos wikis apropriados.

**Comment by fernandowobeto** [comment]
Por mim, bora! Inclusive já abri um PR do tipo DRAFT pra testar.

**Comment by alfsb** [comment]
> Por mim, bora! Inclusive já abri um PR do tipo DRAFT pra testar.

Até para você ver como isso funciona, um PR em Draft não deixa fazer o merge tão facilmente. A tela fica assim:
![image](https://github.com/php/doc-pt_br/assets/10078152/219e1b91-abce-492c-84c1-adfec5d9d432)

Como PR Draft é um pouco mais raro que PR final, acho que isso sinaliza bem, do lado do tradutor e editor, o que/quando fazer o merge.

**Comment by fernandowobeto** [comment]
Boa tarde!
WIP: reference/dom/domentityreference/*

**Comment by fernandowobeto** [comment]
Boa noite!
WIP: reference/dom/domimplementation/*

**Comment by fernandowobeto** [comment]
Bom dia!
WIP: reference/dom/domnamednodemap/*

**Comment by fernandowobeto** [comment]
Boa tarde!
WIP: reference/dom/domnode/*

**Comment by fernandowobeto** [comment]
Boa tarde!
WIP: reference/dom/domnodelist/*

**Comment by fernandowobeto** [comment]
Boa tarde,
bora fazer um "Coordenação 2024"?

**Comment by alfsb** [comment]
> Boa tarde, bora fazer um "Coordenação 2024"?

Boa. E bora. Me pegou literalmente fazendo isso agora. Já já aparece.

**Comment by alfsb** [comment]
Ola @fernandowobeto , eu acho que apaguei uma reserva indevidamente nesse issue aqui. Eu vi a reserva nova no issue novo, mas estou na cabeça que tinha uma reserva aqui em aberto, que era a razão para deixar esse em aberto.

**Comment by fernandowobeto** [comment]
> Ola @fernandowobeto , eu acho que apaguei uma reserva indevidamente nesse issue aqui. Eu vi a reserva nova no issue novo, mas estou na cabeça que tinha uma reserva aqui em aberto, que era a razão para deixar esse em aberto.

Oi, sim, tinha mesmo, mas como a nova issue de 2024 foi aberta, eu exclui ela aqui e adicionei na de 2024. Desculpe se te gerou confusão...

**Comment by fernandowobeto** [comment]
por mim essa aqui já pode ser fechada

**Comment by alfsb** [comment]
Opa, tranquilo. Com esse exaurido, bora para o 2024.
