### ISSUE TITLE
Traduzir "operador spread"

### ISSUE THREAD

**Issue by lhsazevedo** [php/doc-pt_br#49]
Seguindo a sugestão do @rafaelbernard na [tradução](https://github.com/php/web-php/pull/475) da página de lançamento do PHP 8.1, podemos traduzir o nome desse operador como "operador de propagação".

https://github.com/php/doc-pt_br/blob/4149a8647edc1dccf8690214f2db2eceb18c0148/appendices/migration74/new-features.xml#L336

**Comment by rafaelbernard** [comment]
"propagação" é o termo que eu gosto mais porque o que vejo é que ao usar o operador nós propagamos os valores de um determinado vetor para o outro, sem que o vetor de origem seja influenciado pela forma como o de destino vai lidar com eles, ainda que o objetivo seja de que o de destino capture o que vem do primeiro. Eu gosto também do termo propagação porque quase reflete a maneira como duplicações serão consideradas, ou seja, haverá um tipo de mesclagem no que veio progagado. A idéia de ondas propagadas por um roteador de rede para um repetidor de sinal, por exemplo, me parece muito próximo do que acontece na execução deste operador. Propagação também reflete a simetria da operação.

"desmontagem" eu já não gosto tanto porque nenhum dos dois vetores sofrerá um desmonte, então, me parece incompleto, ainda que a gente possa imaginar que as chaves e valores do vetor foram desmontadas no vetor de destino. Mas, na verdade, ele não é simplesmente remontado, afinal, chaves semelhantes nos dois vetores vai gerar um descarte no destino e o de origem se mantém intacto (montado).

"espalhamento" não me agrada. Parece mesmo que ficará simplesmente lançado a esmo para ser recolhido. Perde um pouco o sentido de que sai de que há uma origem e um destino.

**Comment by rafaelbernard** [comment]
Se ajudar:

---
(pro.pa.ga.ção)

sf.

1. Ação ou resultado de propagar(-se)

2. Multiplicação por meio de reprodução, de geração; DIFUSÃO; DISSEMINAÇÃO: propagação de espécies raras da fauna brasileira.

3. Desenvolvimento, proliferação, alastramento (propagação da doença)

4. Divulgação, difusão, vulgarização (propagação de notícias; propagação de ideias)

5. Fís. Transmissão dos imponderáveis através de um meio: Não é possível fazer a propagação do som no vácuo.

---
(des.mon.ta.gem)

sf.

1. Ação ou resultado de desmontar(-se); DESMONTE [ Antôn.: montagem ]

---
(es.pa.lha.men.to)

sm.

1. Ação de espalhar(-se).

2. Fís.nu. Processo em que ocorre a alteração da trajetória de uma partícula (e, possivelmente, de sua energia e às vezes de sua natureza) quando esta interage com outra(s) ou com um núcleo; DIFUSÃO

3. Ópt. Alteração da trajetória de um raio luminoso quando este atravessa um meio que contém partículas capazes de produzir a difração da luz.

**Comment by lhsazevedo** [comment]
Parece que o pessoal da MDN [seguiu com "espalhamento"](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Operators/Spread_syntax) mesmo. 

"Propagação" e "desmontagem" fazem muito sentido e podem até descrever melhor função do operador, mas acredito que "espalhamento" é o mais próximo que temos dos significados da palavra _spread_. Afinal, o nome do operador não é "propagation operator" nem "disassembly operator".

Um debate similar ocorreu na tradução de [Backed Enums](https://github.com/php/doc-pt_br/pull/43). "Enum Tipado" faz sentido pra mim, mas deve haver um motivo pro pessoal do core não ter batizado de "Typed Enum". Seria meu papel de tradutor afastar tanto um nome do original, quando há uma tradução mais próxima, mesmo que faça mais sentido no PHP? E o que faremos se no futuro aparecer um "Typed Enum", "disassembly operator" ou "propagation operator"?

Tenho certeza que vamos achar nomes melhores para todos os termos que surgirem, mas acabaremos com uma tradução muito distante da original, aumentando ainda mais a fragmentação que o @alfsb [comentou aqui](https://github.com/php/doc-pt_br/pull/43#issuecomment-957002228). 

Então meu voto vai para "operador de espalhamento", ciente que talvez não seja o mais bonito ou descreva perfeitamente a funcionalidade, mas é o mais próximo do original.

**Comment by rafaelbernard** [comment]
Primeiramente: grato por me incluir no debate! )))

Concordo. A consistência será mais útil neste caso, já que o termo será reconhecível de desenvolvedores que já o tiverem visto em outras documentações.

**Comment by alfsb** [comment]
>
> Parece que o pessoal da MDN seguiu com "espalhamento"
> <https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Operators/Spread_syntax>
> mesmo.
>
Para vocês verem... Eu mesmo não tinha visto isso, por não acompanhar essa
linguagem. Optaram pelo termo próximo original.

Que se fosse usado pelo termo usado na descrição, seria "operador de
expansão", que é algo perto também do efeito final (expande o array no
ponto onde o operador é chamado).


> Tenho certeza que vamos achar nomes melhores para todos os termos que
> surgirem, mas acabaremos com uma tradução muito distante da original,
> aumentando ainda mais a fragmentação que o @alfsb
> <https://github.com/alfsb> comentou aqui
> <https://github.com/php/doc-pt_br/pull/43#issuecomment-957002228>.
>
> Então meu voto vai para "operador de espalhamento", ciente que talvez não
> seja o mais bonito ou descreva perfeitamente a funcionalidade, mas é o mais
> próximo do original.
>
A história de evitar fragmentação é mais geral, porém é mais facilmente
demonstrável na história dos enums no PHP. Deem uma lida em
https://github.com/Crell/enum-comparison para ver como a fragmentação pode
levar a resultados cômicos e trágicos, no que diz respeito à interpretação
e comparação de terminologias em linguagens.

Se ocorre já aqui numa língua só (inglês), aqui eu lembro que cada tradução
é só mais um vetor potencial para aumentar o problema.

André

>

**Comment by alfsb** [comment]
Incidentalmente eu tive de traduzir a parte do manual que detalha o operado spread. Por enquanto está "expansão", mas não havendo novos comentários, ganhou por votação a terminologia do MDN (espalhamento), e daí eu vou mudar para algo na linha de "Operador de espalhamento (spread operator)" nos títulos, e deixar expansão no texto. Bem na linha do link MDN acima.
