### ISSUE TITLE
Idioma

### ISSUE THREAD

**Issue by ninomartins** [php/doc-pt_br#512]
From manual page: https://php.net/pdo.connections
O idioma em portugues não esta funcionando
---

**Comment by alfsb** [comment]
Esse arquivo de fato não está traduzido, e é uma situação já mapeada, conforme https://github.com/php/doc-pt_br/wiki/Issues-e-perguntas-frequentes#encontrei-um-arquivo-desatualizado-parcialmente-traduzido-ou-errado .

**Comment by leonardolara** [comment]
> ## From manual page: https://php.net/pdo.connections
> O idioma em portugues não esta funcionando

Página agora está disponível em português.
