### ISSUE TITLE
Erro sobre hebraico

### ISSUE THREAD

**Issue by yankl** [php/doc-pt_br#515]
Na página https://www.php.net/manual/pt_BR/language.oop5.paamayim-nekudotayim.php está escrito: 

> Paamayim Nekudotayim pode parecer, de início, uma escolha estranha para chamar dois pontos duplos. No entanto, na hora de escrever o Motor Zend 0.5 (que equipa o PHP 3), foi como a equipe da Zend decidiu chamá-lo. Na verdade, vem do hebraico e significa "double colon" (**referindo-se ao cólon do intestino e não aos dois-pontos - palavra com duplo significado em inglês**).

Mas não há aqui referência alguma ao cólon. 'Paamayim Nekudotayim' significa em hebraico literalmente 'duas vezes dois-pontos'. Há duplo significado da palavra 'colon' _em inglês_ mas não na palavra hebraica, que é o sujeito deste parágrafo.

**Comment by leonardolara** [comment]
Obrigado pela observação, corrigido no texto. Creio que houve engano ao usar o tradutor de hebraico para português diretamente.
