### ISSUE TITLE
where is a list of all formats?

### ISSUE THREAD

**Issue by agenciadiz** [php/doc-pt_br#53]
From manual page: https://php.net/function.date

---

**Comment by agenciadiz** [comment]
> This is most likely a translation issue. The pt_BR translation for `date()` states:
> 
> > Formato aceito pela DateTimeInterface::format().
> 
> But the `DateTimeInterface::format()` does not list the formats.
> 
> @agenciadiz, use the English documentation for now: https://www.php.net/manual/en/datetime.format.php

tks

**Comment by lhsazevedo** [comment]
Thanks for reporting @agenciadiz, we'll fix it asap.
