### ISSUE TITLE
Revisão e conversão do wiki

### ISSUE THREAD

**Issue by alfsb** [php/doc-pt_br#702]
Da discussão recente no tópico de Coordenação, sobre renovar e converter o wiki, eu parei para dar uma boa olhada no wiki atual, e disso tive duas impressões:

1. Há um tanto de coisas a revisar sim (tem coisas antigas como editores de texto que nem exitem mais);
2. Fiquei na dúvida se partimos mesmo para conversão, ou deixa como está.

O maior problema de sair do wiki para markdown é que perde-se a interface wiki, que é menos poluída que o normal GitHub. É mais focada no texto. Se souberem de alguma forma e fazer uma pasta com markdown ser exibida de maneira mais limpa na interface GitHub ou de terceiros, isso resolveria.

Outra questão é onde colocar o markdown. Eu imagino que criar um `.docs/guia-resumido/` resolva, já que o revcheck *novo* ignora dotflies, e ter um `guia-resumido` abre espaço daí para ter um `guia-completo`, que fosse a tradução do dochowto.

---

Estas questões continuam em aberto, mas eu puxei para mim de atualizar o wiki. Progresso:

- [x] Home
- [x] Editores de texto
- [x] Guia de edição do manual // 60% completo
- [x] Issues e perguntas frequentes
- [x] Prioridades
- [x] Roteiro git
- [x] Roteiro web
- [x] Tag de revisão
- [x] Teste de pull requests

**Comment by alfsb** [comment]
Puxando para mim a atualização do wiki.

Por enquanto hospedando os textos no próprio wiki até uma indicação de funcionalidade, que permita exibir documentos markdown hospedados no GitHub em uma interface mais limpa..

**Comment by alfsb** [comment]
Apenas para avisar. Terminei, finalmente, a revisão do roteiro git. Na parte principal não mudou muita coisa, mas é bom reler para refrescar e ver se está tudo certo.

O que mudou realmente foi dois anexos acrescentados. Eles tratam de tópicos avançados, mas eu tentei deixar acessível para iniciantes. Eu até acredito que eles estão bons, mas peço encarecidamente que pessoal experiente em git de uma boa olhada neles para ver se não tem coisas erradas, comandos e mesmo conceitual.

**Comment by alfsb** [comment]
Revisão terminada. Novamente, peço a leitura, e até para além disso, alterações, por parte dos tradutores mais ativos, que se tornaram equipe de tradução de fato.

A única coisa que está faltando revisar são os scritps utilitários, e aqui eu preciso perguntar. Tem alguém usando eles, e se sim, qual o estilo de trabalho que você adota no dia a dia da tradução?

1. Tudo no `master`, `rebase` ligado, uma alteração por vez.
2. Tudo em branchs, `rebase` desligado, várias alterações em paralelo.
3. Outro estilo?

Isso porque as ferramentas estão direcionadas para o estilo "1", e meio que não avisam disso. É um estilo de uso que parece apropriado a iniciantes, mas meio que obriga a só fazer uma alteração por vez. E tem a desvantagem que em qualquer conflito, o git **vai** por o clone em um estado de rebase conflitado, que é muito assustador ao iniciante.

Antes eu era mais a favor do rebase ligado, hoje menos. Mas não quero sair alterando essa parte dos comandos se tem usuários que usam e preferem rebase ligado.

**Comment by leonardolara** [comment]
> Revisão terminada. Novamente, peço a leitura, e até para além disso, alterações, por parte dos tradutores mais ativos, que se tornaram equipe de tradução de fato.
> 
> A única coisa que está faltando revisar são os scritps utilitários, e aqui eu preciso perguntar. Tem alguém usando eles, e se sim, qual o estilo de trabalho que você adota no dia a dia da tradução?
> 
> 1. Tudo no `master`, `rebase` ligado, uma alteração por vez.
> 2. Tudo em branchs, `rebase` desligado, várias alterações em paralelo.
> 3. Outro estilo?
> 
> Isso porque as ferramentas estão direcionadas para o estilo "1", e meio que não avisam disso. É um estilo de uso que parece apropriado a iniciantes, mas meio que obriga a só fazer uma alteração por vez. E tem a desvantagem que em qualquer conflito, o git **vai** por o clone em um estado de rebase conflitado, que é muito assustador ao iniciante.
> 
> Antes eu era mais a favor do rebase ligado, hoje menos. Mas não quero sair alterando essa parte dos comandos se tem usuários que usam e preferem rebase ligado.

Eu costumo alterar tudo no `master`, `rebase` ligado. Gosto de fazer as alterações em série.
Depois das alterações, uso os scripts utilitários para ter certeza que não ficou nada incoerente, faço add, commit, push e parto para a próxima.

Quando estava fazendo em paralelo, notei que as atualizações eram bem frequentes no manual em inglês, e isso dava muito trabalho para deixar todos oso branches atualizados (para não ter que revisar mais uma vez, com mais um rev tag).

**Comment by alfsb** [comment]
Nesse caso, vou manter esse estilo nos scripts utilitários. Eu já até fiz uma mexida neles, mas ainda mantendo o estilo tudo no `master`, `rebase ligado. O que daí, finaliza a revisão do meu lado.

Mas aproveitando que você é bem ativo e usa esse estilo, dá uma olhada no passo final do https://github.com/php/doc-pt_br/wiki/Roteiro-web#depois-que-o-seu-pull-request-%C3%A9-aceito . Só para confirmar que os procedimentos após pull request são aqueles mesmo, e no case de alterações seriais, o GitHub consegue não detecta os repositórios upstream e fork em situação de conflito, após um merge e/ou squashed merge no upstream.

**Comment by alfsb** [comment]
Aliás, fiz umas últimas alterações, basicamente removendo configurações que podem "vazar" de um script, caso ele seja executado através de `source` ao invés de sub comando. Veja(m) se não quebrou nada no dia a dia de vocês, e após isso, podem fechar esse issue.

Eu estou um tanto afastado da tradução em si nesse último ano, e devo ficar ausente por um tempo grande ainda, para conseguir focar em uns projetos grandes de infraestrutura do manual (os tantos PR abertos no `doc-base`). Ainda var ter umas mexidas nos scripts de sincronia de XML (aqueles chamados no `all.sh`), que é outra coisa que deve tomar um bom tempo também, já que deve rolar muitos pequenos ajustes para torná-los úteis a mais linguagens.
