### ISSUE TITLE
Correção de uma palavra

### ISSUE THREAD

**Issue by AyrtonG94** [php/doc-pt_br#703]
Nessa página https://github.com/php/doc-pt_br/blob/master/reference/pdo/pdostatement/debugdumpparams.xml

a linha 7 está escrito "isntrução" ao invés de instrução.

**Comment by leonardolara** [comment]
Corrigido no [e0d192e](https://github.com/php/doc-pt_br/commit/e0d192e6ef2ec6aab12cef632ba1b910490c5c87)
